### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by vaishakhpj** [MichaelRocks/paranoid#16] opened 2018-06-06 09:11 UTC
Compilation error:
E:\Username\FolderName\AppName\app\build\tmp\transformClassesWithParanoidForDebug\src\io\michaelrocks\paranoid\Deobfuscator$app$Debug.java:3:8: too many constants

Caused by: io.michaelrocks.paranoid.processor.ParanoidException: Compilation error:
E:\Username\FolderName\AppName\app\build\tmp\transformClassesWithParanoidForDebug\src\io\michaelrocks\paranoid\Deobfuscator$app$Debug.java:3:8: too many constants
	at io.michaelrocks.paranoid.processor.Generator.generateDeobfuscator(Generator.kt:73)

This error comes when i compile after using 0.2.2 , i have lot of string constants to obfuscate.Please help and look in to the issue

**Comment by MichaelRocks** [comment] 2018-06-07 09:01
Hi @vaishakhpj and thank you for reporting this issue. Seems you really have quite a lot of string constants. Could you tell me approximately how many constants you have?

**Comment by vaishakhpj** [comment] 2018-06-07 11:30
Hi i have around 750 String constants which needs to be obfuscated. Thanks for fast reply.

**Comment by vaishakhpj** [comment] 2018-06-08 05:59
can you refactor constants as LinkedList ,so i think it can overcome number of constant limits 
[https://stackoverflow.com/questions/3767979/how-much-data-can-a-list-can-hold-at-the-maximum](https://stackoverflow.com/questions/3767979/how-much-data-can-a-list-can-hold-at-the-maximum)
[https://stackoverflow.com/questions/7632126/maximum-size-of-hashset-vector-linkedlist](https://stackoverflow.com/questions/7632126/maximum-size-of-hashset-vector-linkedlist)

**Comment by MichaelRocks** [comment] 2018-06-08 06:15
The problem is a bit more complicated. Constants mentioned in the compilation error is a constant pool, which is an internal structure in a .class file. And it becomes too large because methods in `Deobfuscator` class use too many integer constants. I have an idea how to fix it and will try it soon.

**Comment by vaishakhpj** [comment] 2018-06-12 05:46
Hi can you make a simple plugin instead of this,
Steps
-just replace all strings with an encrypted value using a key given in build.gradle file
-And to decrypt , we want to get that key from server ( it can be easily done using firebase).
-So for that make an initialization of this library in app using downloaded key before accessing these decrypted strings values

This will be very useful for everybody since this is what everybody is now doing in their app but there is no free or opensource plugin available , i am a beginner in gradle scripts so i am not yet good at making a plugin, can you help

**Comment by MichaelRocks** [comment] 2018-06-12 12:06
@vaishakhpj I thought about something similar but my idea was to provide an easy way for users to implement their own obfuscators. Anyway such change would require significant redesign of this project. While I believe it will happen some day I can say for sure this functionality will not appear very soon.

What about your issue, I have a fix for it and it'll be available in just a couple of minutes.

**Comment by vaishakhpj** [comment] 2018-06-15 13:16
Hi i am getting this error while compiling, Please help

(Caused by: java.lang.NoSuchMethodError: kotlin.collections.CollectionsKt.shuffled(Ljava/lang/Iterable;)Ljava/util/List;
	at io.michaelrocks.paranoid.processor.Generator.generateDeobfuscatorSourceCode(Generator.kt:84))

**Detailed Error Below**

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithParanoidForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: kotlin.collections.CollectionsKt.shuffled(Ljava/lang/Iterable;)Ljava/util/List;
	at io.michaelrocks.paranoid.processor.Generator.generateDeobfuscatorSourceCode(Generator.kt:84)
	at io.michaelrocks.paranoid.processor.Generator.generateDeobfuscator(Generator.kt:39)
	at io.michaelrocks.paranoid.processor.ParanoidProcessor.process(ParanoidProcessor.kt:55)
	at io.michaelrocks.paranoid.plugin.ParanoidTransform.transform(ParanoidTransform.kt:62)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 32 more

**Comment by MichaelRocks** [comment] 2018-06-15 18:21
Do you use Kotlin in your project? And if yes which version of Kotlin?

**Comment by vaishakhpj** [comment] 2018-06-16 07:09
yes, ext.kotlin_version = '1.2.50', i added kotlin for supporting this library when this error came but still showing error, previously worked without adding kotlin

**Comment by Ahmed-Ganna** [comment] 2018-06-27 19:17
I have this issue too

**Comment by waxtah** [comment] 2018-06-28 10:30
:android:transformClassesWithParanoidForRelease FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':android:transformClassesWithParanoidForRelease'.
> kotlin.collections.CollectionsKt.shuffled(Ljava/lang/Iterable;)Ljava/util/List;

**Comment by waxtah** [comment] 2018-06-28 10:32
It looks like Gradle use old Kotlin version (< 1.2+). I have no idea, how to point right version.

**Comment by waxtah** [comment] 2018-06-28 16:38
My solution was upgrage gradle version to 4.7 in gradle-wrapper.properties

**Comment by MichaelRocks** [comment] 2018-06-29 14:48
Seems it could be a good idea to bundle Kotlin SDK within the plugin. I'll try to do that soon.

**Comment by MichaelRocks** [comment] 2018-07-03 07:46
Should be fixed now.

**Closed as completed by MichaelRocks** 2018-07-03 07:46 UTC
Labels: bug
