### ISSUE TITLE
How to make it obfuscate string all class without use anotation?

### ISSUE THREAD

**Issue by tracer8** [MichaelRocks/paranoid#36] opened 2020-08-14 10:29 UTC
Hi,
I want to obfuscate string on every class in my project. How can i do that without adding @Obfuscate on all class?
If this feature is not available, where can i fast modify your code to make it?
Thank you!

**Comment by MichaelRocks** [comment] 2020-08-14 11:47
Hi,

This is a duplicate of #23. If you want to make you fork without `@Obfuscate` I believe you can assume that `@Obfuscate` is applied to every class [here](https://github.com/MichaelRocks/paranoid/blob/master/processor/src/main/kotlin/io/michaelrocks/paranoid/processor/Patcher.kt#L80). But I'm going to make a change in the library quite soon that will allow to configure obfuscation from build.gradle.

**Closed as completed by MichaelRocks** 2020-08-14 11:47 UTC
